---

vscode_plugins:
  # ----------------------------------------------------------------------------
  # Common
  # ----------------------------------------------------------------------------
  - alefragnani.bookmarks
  - ms-ceintl.vscode-language-pack-ja
  - ms-vscode-remote.vscode-remote-extensionpack
  - nmsmith89.incrementor
  - shardulm94.trailing-spaces
  - streetsidesoftware.code-spell-checker
  - tomoki1207.vscode-input-sequence
  - tyriar.sort-lines
  - wmaurer.change-case
  - wraith13.bracket-lens
  #
  #
  # ----------------------------------------------------------------------------
  # Binary
  # ----------------------------------------------------------------------------
  - ms-vscode.hexeditor
  #
  #
  # ----------------------------------------------------------------------------
  # C++
  # ----------------------------------------------------------------------------
  - ajshort.include-autocomplete
  - mine.cpplint
  - ms-vscode.cpptools
  - twxs.cmake
  - xaver.clang-format
  #
  #
  # ----------------------------------------------------------------------------
  # CSV
  # ----------------------------------------------------------------------------
  - grapecity.gc-excelviewer
  - mechatroner.rainbow-csv
  #
  #
  # ----------------------------------------------------------------------------
  # Docker
  # ----------------------------------------------------------------------------
  - exiasr.hadolint
  - ms-azuretools.vscode-docker
  #
  #
  # ----------------------------------------------------------------------------
  # Geospatial
  # ----------------------------------------------------------------------------
  - jumpinjackie.vscode-map-preview
  #
  #
  # ----------------------------------------------------------------------------
  # Git
  # ----------------------------------------------------------------------------
  - mhutchie.git-graph
  #
  #
  # ----------------------------------------------------------------------------
  # Graphviz
  # ----------------------------------------------------------------------------
  - joaompinto.vscode-graphviz
  #
  #
  # ----------------------------------------------------------------------------
  # Jenkins
  # ----------------------------------------------------------------------------
  - ivory-lab.jenkinsfile-support
  #
  #
  # ----------------------------------------------------------------------------
  # Markdown
  # ----------------------------------------------------------------------------
  - davidanson.vscode-markdownlint
  - goessner.mdmath
  - shuworks.vscode-table-formatter
  #
  #
  # ----------------------------------------------------------------------------
  # PDF
  # ----------------------------------------------------------------------------
  - tomoki1207.pdf
  #
  #
  # ----------------------------------------------------------------------------
  # Protocol buffers
  # ----------------------------------------------------------------------------
  - zxh404.vscode-proto3
  #
  #
  # ----------------------------------------------------------------------------
  # Python
  # ----------------------------------------------------------------------------
  - charliermarsh.ruff
  - matangover.mypy
  - ms-python.python
  - ms-python.vscode-pylance
  #
  #
  # ----------------------------------------------------------------------------
  # Rust
  # ----------------------------------------------------------------------------
  - rust-lang.rust-analyzer
  #
  #
  # ----------------------------------------------------------------------------
  # SVG
  # ----------------------------------------------------------------------------
  - simonsiefke.svg-preview
  #
  #
  # ----------------------------------------------------------------------------
  # Shell script
  # ----------------------------------------------------------------------------
  - foxundermoon.shell-format
  - timonwong.shellcheck
  #
  #
  # ----------------------------------------------------------------------------
  # TOML
  # ----------------------------------------------------------------------------
  - be5invis.toml
  #
  #
  # ----------------------------------------------------------------------------
  # Xml
  # ----------------------------------------------------------------------------
  - dotjoshjohnson.xml
  #
  #
  # ----------------------------------------------------------------------------
  # YAML
  # ----------------------------------------------------------------------------
  - redhat.vscode-yaml
  #
  #
  # ----------------------------------------------------------------------------
  # yUML
  # ----------------------------------------------------------------------------
  - jaimeolivares.yuml
