name: CI

on: [push, pull_request]

jobs:
  static_code_analysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r develop.requirements.txt
      - run: black --check
      - run: isort --check .
  status_check:
    runs-on: ubuntu-20.04
    needs:
      - static_code_analysis
    steps:
      - run: echo 'pass'
