name: CI

on: [push, pull_request]

jobs:
  static_code_analysis:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck
        run: find . -name '*.sh' | xargs -t shellcheck
  status_check:
    runs-on: ubuntu-20.04
    needs:
      - static_code_analysis
    steps:
      - run: echo 'pass'
